//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeProcessor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeProcessor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		.
        /// </summary>
        internal static string String_ {
            get {
                return ResourceManager.GetString("String_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  a .
        /// </summary>
        internal static string String__a_ {
            get {
                return ResourceManager.GetString("String__a_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  as a .
        /// </summary>
        internal static string String__as_a_ {
            get {
                return ResourceManager.GetString("String__as_a_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  based on .
        /// </summary>
        internal static string String__based_on_ {
            get {
                return ResourceManager.GetString("String__based_on_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can: .
        /// </summary>
        internal static string String_can__ {
            get {
                return ResourceManager.GetString("String_can__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In .
        /// </summary>
        internal static string String_In_ {
            get {
                return ResourceManager.GetString("String_In_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to react to: .
        /// </summary>
        internal static string String_react_to__ {
            get {
                return ResourceManager.GetString("String_react_to__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	.
        /// </summary>
        internal static string String_tab {
            get {
                return ResourceManager.GetString("String_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		 =&gt; .
        /// </summary>
        internal static string String_tab_arrow {
            get {
                return ResourceManager.GetString("String_tab_arrow", resourceCulture);
            }
        }
    }
}
